### ISSUE TITLE
Does this damage Bitcoin's fungibility as a currency

### ISSUE THREAD

**Issue by yzernik** [casey/sat-tracker#18]
If I have a wallet with multiple utxo's, I would have to be careful to not spend the utxo's associated with more valuable atoms, right?

**Comment by casey** [comment]
That's correct. However, I think the way that it would work in practice is that most atoms aren't worth anything, so people just ignore them. And for people who don't ignore them, they'll use special wallets for their atom holdings that use the transfer rule (whatever form it takes) to keep them in the wallet.

**Comment by casey** [comment]
I kind of think that this doesn't matter, i.e. atoms are specifically designed to be both non-fungible but ignorable.

Privacy is another issue which is separate but related.

**Comment by yzernik** [comment]
That makes sense. I guess fungibility would only be a problem if merchants don't accept a utxo because it is associated with a certain atom.

Like if someone draws a doodle on a dollar bill, you can still spend it most places.

**Comment by casey** [comment]
> That makes sense. I guess fungibility would only be a problem if merchants don't accept a utxo because it is associated with a certain atom.

That's right, and atoms can be accidentally attached to a coin, so there's some level of plausible deniability.

> Like if someone draws a doodle on a dollar bill, you can still spend it most places.

Yeah, exactly.

**Comment by casey** [comment]
Yolo y'all
